### ISSUE TITLE
KeyError: 'feed' when using format other than 'json'

### ISSUE THREAD

**Issue by chuckwondo** [nasa/python_cmr#42]
When performing a query with a format other than `"json"`, a `KeyError` is raised.

```plain
$ python -c "import cmr; cmr.queries.GranuleQuery().format('umm_json').short_name('MOD02QKM').get(1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python_cmr/cmr/queries.py", line 73, in get
    if page_size > len(response.json()['feed']['entry']) or len(results) >= limit:
                       ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'feed'
```

**Comment by chuckwondo** [comment]
> I'll submit a PR for this, as I see there's also a problem with the logic in the `get` method regarding counting results for non-`json` formats as well. Specifically, for non-`json` formats, the length of the results list is equal to the number of _pages_ fetched (i.e., the number or requests), _not_ the number of _items_ fetched. For example, for a non-`json` format, if I want to get 10 items, I actually get 10 _pages_ of items. Given that the page size is 2000, this means I will actually get 20,000 items, not 10 items.

Correction: I don't get 10 pages of 2000 items, I get 10 pages of 10 items. So I get only 100 items, not 20,000, but still, I'm getting many more items than I want. Generally, instead of getting only `n` items, I'm getting `n^2` items when `n <= 2000`, and `2000 * n` items when `n > 2000`.
